reminder/profiles/urls.py
from django.conf.urls import url, include
from profiles import views


urlpatterns = [
    url(r'^$', views.index, name='profiles'),
    url(r'^register/$',views.register , name='register'),
    url(r'^login/$', views.authentication, name='authentication'),
]

reminder/register/urls.py
from django.conf.urls import url
from register import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.authentication, name='login')
]

reminder/reminder/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('profiles.urls', namespace='profiles')),
    url(r'^reminder/', include('reminders.urls', namespace='reminders')),
    url(r'^register/', include('register.urls', namespace='register')),
]

reminder/reminders/urls.py
from django.conf.urls import url
from reminders import views
urlpatterns = [
    url(r'^$', views.add_group, name='group'),
    url(r'^(?P<group_id>[0-9]+)/reminders_add/$', views.add_reminders, name='reminder'),
    url(r'(?P<group_idi>[0-9]+)/group$', views.group_page, name='reminderss'),
    url(r'(?P<del_id>[0-9]+)/delete_remind$', views.del_remind, name='delremind'),
<<<<<<< HEAD
=======
    url(r'(?P<profile_id>[0-9]+)/add_profile/$', views.app_profile, name='addprofile'),
    url(r'(?P<rm_page>[0-9]+)/rm_page/$', views.reminder_page, name='rm_page'),
    # url(r'(?P<pr_id>[0-9]+)/add_profiles/$', views.add_profile, name='addprofiles'),
>>>>>>> 6d41f6ffd4e1792d33b648479b9aa46594dd99df
]

reminder/templates/main/index.html
<a href="{% url 'reminders:group' %}">Создать группу</a>	
<p>{{request.user.username}}</p>
<<<<<<< HEAD
Напоминании: {% for i in request.user.profile.all %}
{% for i in i.reminder.all %}
  <p>{{ i.name }}    дата: {{ i.date_of_publish }}
<a href="{% url 'reminders:delremind' i.id %}">&times;</a>
{% endfor %}	
{% endfor %}
=======



Напоминании:
{% for i in request.user.reminder.all %}
  <p><a href="{% url 'reminders:rm_page' i.id %}">{{ i.name }}    дата: {{ i.date_of_publish }}</a>


{% endfor %}
	


>>>>>>> 6d41f6ffd4e1792d33b648479b9aa46594dd99df
<p>Мои группы:</p>
{% for i in request.user.profile.all %}
	
<a href="{% url 'reminders:reminderss' i.id  %}">{{ i.name }}</a>
{% endfor %} 
<<<<<<< HEAD
	
=======
<a href="{% url 'register:register' %}">Регистрация</a>
<a href="{% url 'register:login' %}">Авторизация</a>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}
>>>>>>> 6d41f6ffd4e1792d33b648479b9aa46594dd99df